# Site settings
title: Soumyadeep Das 
subtitle: Homepage
tagline: Astrophysics. AGN. Interferometry. I am an incoming PhD Student at ICRAR/UWA Perth.
email: soumyadeep.das.phy14@iitbhu.ac.in
description: Astrophysics. AGN. Interferometry. I am an incoming PhD Student at ICRAR/UWA Perth. I am interested in multiwavelength AGN research, studies of evolutionary path of radio galaxies, AGN restart, and the role of the host environment on AGN life-cycle. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thephoenix01.github.io" # the base hostname & protocol for your site
logo: assets/images/favicon.png


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 1.0.1

author:
    name: Soumyadeep Das
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    # author-bio : "Incoming PhD Student at ICRAR/UWA Perth."
    author-bio : "Graduated with Dual Degree (B.Tech. and M.Tech.) in Engg. Physics, IIT Varanasi, India."
    ads : https://ui.adsabs.harvard.edu/search/p_=0&q=orcid%3A0000-0002-3493-6638&sort=date%20desc%2C%20bibcode%20desc
    facebook: https://www.facebook.com/TheSoumyadeepDas
    github: https://github.com/thephoenix01
    gitlab: 
    googleplus: 
    googlescholar : https://scholar.google.com/citations?user=02NSBH4AAAAJ&hl=en
    instagram: https://www.instagram.com/_thephoenix01_/
    linkedin: https://www.linkedin.com/in/soumyadeep01
    orcid: https://orcid.org/0000-0002-3493-6638
    pinterest:
    slack:
    stackoverflow : https://stackoverflow.com/users/4701760/thephoenix01
    steam : https://steamcommunity.com/profiles/76561198859680680
    twitter: https://twitter.com/thephoenix01

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
