# Site settings
title: Soumyadeep Das 
subtitle: Homepage
tagline: I am Soumyadeep Das, an incoming PhD Student at ICRAR/UWA Perth, interested in Astrophysics, AGN, Interferometry.
email: soumyadeep.das.m44@gmail.com
description: I am Soumyadeep Das, an incoming PhD Student at ICRAR/UWA Perth. I am interested in multiwavelength AGN research, AGN life-cycle, restarts, and the host environment. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://soumyadeepdas.gitlab.io" # the base hostname & protocol for your site
logo: assets/images/favicon.png
image: assets/images/og-pic.jpg


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 4.5.0

author:
    name: Soumyadeep Das
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    # author-bio : "Incoming PhD Student at ICRAR/UWA Perth."
    author-bio : "Graduated with Dual Degree (B.Tech. and M.Tech.) in Engg. Physics, IIT Varanasi, India."
    ads : https://ui.adsabs.harvard.edu/search/p_=0&q=orcid%3A0000-0002-3493-6638&sort=date%20desc%2C%20bibcode%20desc
    facebook: https://www.facebook.com/TheSoumyadeepDas
    github: https://github.com/lordparthurnaax
    gitlab: https://gitlab.com/lordparthurnaax
    googleplus: 
    googlescholar : https://scholar.google.com/citations?user=02NSBH4AAAAJ&hl=en
    instagram: https://www.instagram.com/lordparthurnaax/
    linkedin: https://www.linkedin.com/in/soumyadeep01
    orcid: https://orcid.org/0000-0002-3493-6638
    pinterest:
    researchgate: https://www.researchgate.net/profile/Soumyadeep_Das9
    slack:
    stackoverflow : https://stackoverflow.com/users/4701760/lordparthurnaax
    steam : https://steamcommunity.com/profiles/76561198859680680
    twitter: https://twitter.com/lordparthurnaax

# Social for SEO
twitter: 
  username: lordparthurnaax
  card: summary_large_image

facebook:
  app_id: 3425901884091023
  publisher: 3425901884091023   
  admins: 3425901884091023

social:
  name: Soumyadeep Das
  links:
    - https://twitter.com/lordparthurnaax
    - https://www.instagram.com/lordparthurnaax/
    - https://www.facebook.com/TheSoumyadeepDas
    - https://github.com/lordparthurnaax
    - https://gitlab.com/lordparthurnaax
    - https://www.linkedin.com/in/soumyadeep01

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-redirect-from

# Build settings
markdown: kramdown



exclude:
  - vendor  
